### ISSUE TITLE
docker image deployment

### ISSUE THREAD

**Issue by aremazeilles** [dzhvansky/pepato#12]
In the next stage of the eurobench integration, (described [here](https://github.com/aremazeilles/eurobench_documentation/blob/docker_generation/modules/ROOT/pages/pi_spec.adoc#4-code-deployment-methodology)), we are progressively doing the following:

* making a fork of the repository in [eurobench namespace](https://github.com/eurobench)
* from there deploy the generated docker image onto a [eurobench docker hub](https://hub.docker.com/u/eurobenchtest)

Which is from here the system will get the images that will be used for making the metric computation.

Your repository is currently private. I was wondering if it would be acceptable to turn it to public, or whether you have concerns on this.

**Comment by dzhvansky** [comment]
Done! I suggest solving the problem with pi output types before the fork.

**Comment by aremazeilles** [comment]
Great, so now I see it as public. 
I will start preparing the fork. We can still later makes some updates of the code, don 't worry
